/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CeloRaffle {
  export type AgentIdentityStruct = {
    agentId: BytesLike;
    metadata: string;
    operator: AddressLike;
    active: boolean;
    registeredAt: BigNumberish;
  };

  export type AgentIdentityStructOutput = [
    agentId: string,
    metadata: string,
    operator: string,
    active: boolean,
    registeredAt: bigint
  ] & {
    agentId: string;
    metadata: string;
    operator: string;
    active: boolean;
    registeredAt: bigint;
  };
}

export interface CeloRaffleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activateAgent"
      | "activeAgentId"
      | "agentRegistry"
      | "getAgent"
      | "getParticipantCount"
      | "getParticipants"
      | "getPrizePool"
      | "getRaffleInfo"
      | "getUserTickets"
      | "owner"
      | "participants"
      | "purchaseTickets"
      | "raffleId"
      | "rafflePrizePool"
      | "raffleState"
      | "raffleWinner"
      | "registerAgent"
      | "renounceOwnership"
      | "requestDraw"
      | "setTicketPrice"
      | "startNewRaffle"
      | "ticketCount"
      | "ticketPrice"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentActivated"
      | "AgentRegistered"
      | "DrawCompleted"
      | "OwnershipTransferred"
      | "RaffleClosed"
      | "RaffleStarted"
      | "TicketPriceUpdated"
      | "TicketPurchased"
      | "WinnerSelected"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activateAgent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "activeAgentId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentRegistry",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getAgent", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getParticipantCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipants",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPrizePool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRaffleInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTickets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "participants",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseTickets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "raffleId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rafflePrizePool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "raffleState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "raffleWinner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestDraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTicketPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startNewRaffle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ticketCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ticketPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "activateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeAgentId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getParticipantCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPrizePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRaffleInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "participants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "raffleId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rafflePrizePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "raffleState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "raffleWinner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestDraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTicketPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startNewRaffle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ticketCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ticketPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AgentActivatedEvent {
  export type InputTuple = [agentId: BytesLike];
  export type OutputTuple = [agentId: string];
  export interface OutputObject {
    agentId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agentId: BytesLike,
    operator: AddressLike,
    metadata: string
  ];
  export type OutputTuple = [
    agentId: string,
    operator: string,
    metadata: string
  ];
  export interface OutputObject {
    agentId: string;
    operator: string;
    metadata: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DrawCompletedEvent {
  export type InputTuple = [raffleId: BigNumberish, randomWord: BigNumberish];
  export type OutputTuple = [raffleId: bigint, randomWord: bigint];
  export interface OutputObject {
    raffleId: bigint;
    randomWord: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RaffleClosedEvent {
  export type InputTuple = [raffleId: BigNumberish];
  export type OutputTuple = [raffleId: bigint];
  export interface OutputObject {
    raffleId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RaffleStartedEvent {
  export type InputTuple = [raffleId: BigNumberish];
  export type OutputTuple = [raffleId: bigint];
  export interface OutputObject {
    raffleId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TicketPriceUpdatedEvent {
  export type InputTuple = [newPrice: BigNumberish];
  export type OutputTuple = [newPrice: bigint];
  export interface OutputObject {
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TicketPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    amount: BigNumberish,
    raffleId: BigNumberish
  ];
  export type OutputTuple = [buyer: string, amount: bigint, raffleId: bigint];
  export interface OutputObject {
    buyer: string;
    amount: bigint;
    raffleId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerSelectedEvent {
  export type InputTuple = [
    winner: AddressLike,
    prize: BigNumberish,
    raffleId: BigNumberish
  ];
  export type OutputTuple = [winner: string, prize: bigint, raffleId: bigint];
  export interface OutputObject {
    winner: string;
    prize: bigint;
    raffleId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CeloRaffle extends BaseContract {
  connect(runner?: ContractRunner | null): CeloRaffle;
  waitForDeployment(): Promise<this>;

  interface: CeloRaffleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activateAgent: TypedContractMethod<
    [_agentId: BytesLike],
    [void],
    "nonpayable"
  >;

  activeAgentId: TypedContractMethod<[], [string], "view">;

  agentRegistry: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, boolean, bigint] & {
        agentId: string;
        metadata: string;
        operator: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  getAgent: TypedContractMethod<
    [_agentId: BytesLike],
    [CeloRaffle.AgentIdentityStructOutput],
    "view"
  >;

  getParticipantCount: TypedContractMethod<[], [bigint], "view">;

  getParticipants: TypedContractMethod<[], [string[]], "view">;

  getPrizePool: TypedContractMethod<[], [bigint], "view">;

  getRaffleInfo: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        _raffleId: bigint;
        _state: bigint;
        _participantCount: bigint;
        _prizePool: bigint;
        _ticketPrice: bigint;
      }
    ],
    "view"
  >;

  getUserTickets: TypedContractMethod<[_user: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  participants: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  purchaseTickets: TypedContractMethod<
    [_numTickets: BigNumberish],
    [void],
    "payable"
  >;

  raffleId: TypedContractMethod<[], [bigint], "view">;

  rafflePrizePool: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  raffleState: TypedContractMethod<[], [bigint], "view">;

  raffleWinner: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  registerAgent: TypedContractMethod<
    [_agentId: BytesLike, _metadata: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestDraw: TypedContractMethod<[], [void], "nonpayable">;

  setTicketPrice: TypedContractMethod<
    [_price: BigNumberish],
    [void],
    "nonpayable"
  >;

  startNewRaffle: TypedContractMethod<[], [void], "nonpayable">;

  ticketCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  ticketPrice: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activateAgent"
  ): TypedContractMethod<[_agentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "activeAgentId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "agentRegistry"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, boolean, bigint] & {
        agentId: string;
        metadata: string;
        operator: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [_agentId: BytesLike],
    [CeloRaffle.AgentIdentityStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getParticipantCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getParticipants"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPrizePool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRaffleInfo"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        _raffleId: bigint;
        _state: bigint;
        _participantCount: bigint;
        _prizePool: bigint;
        _ticketPrice: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserTickets"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "participants"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "purchaseTickets"
  ): TypedContractMethod<[_numTickets: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "raffleId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rafflePrizePool"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "raffleState"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "raffleWinner"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [_agentId: BytesLike, _metadata: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestDraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTicketPrice"
  ): TypedContractMethod<[_price: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startNewRaffle"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ticketCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "ticketPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AgentActivated"
  ): TypedContractEvent<
    AgentActivatedEvent.InputTuple,
    AgentActivatedEvent.OutputTuple,
    AgentActivatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DrawCompleted"
  ): TypedContractEvent<
    DrawCompletedEvent.InputTuple,
    DrawCompletedEvent.OutputTuple,
    DrawCompletedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RaffleClosed"
  ): TypedContractEvent<
    RaffleClosedEvent.InputTuple,
    RaffleClosedEvent.OutputTuple,
    RaffleClosedEvent.OutputObject
  >;
  getEvent(
    key: "RaffleStarted"
  ): TypedContractEvent<
    RaffleStartedEvent.InputTuple,
    RaffleStartedEvent.OutputTuple,
    RaffleStartedEvent.OutputObject
  >;
  getEvent(
    key: "TicketPriceUpdated"
  ): TypedContractEvent<
    TicketPriceUpdatedEvent.InputTuple,
    TicketPriceUpdatedEvent.OutputTuple,
    TicketPriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TicketPurchased"
  ): TypedContractEvent<
    TicketPurchasedEvent.InputTuple,
    TicketPurchasedEvent.OutputTuple,
    TicketPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "WinnerSelected"
  ): TypedContractEvent<
    WinnerSelectedEvent.InputTuple,
    WinnerSelectedEvent.OutputTuple,
    WinnerSelectedEvent.OutputObject
  >;

  filters: {
    "AgentActivated(bytes32)": TypedContractEvent<
      AgentActivatedEvent.InputTuple,
      AgentActivatedEvent.OutputTuple,
      AgentActivatedEvent.OutputObject
    >;
    AgentActivated: TypedContractEvent<
      AgentActivatedEvent.InputTuple,
      AgentActivatedEvent.OutputTuple,
      AgentActivatedEvent.OutputObject
    >;

    "AgentRegistered(bytes32,address,string)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "DrawCompleted(uint256,uint256)": TypedContractEvent<
      DrawCompletedEvent.InputTuple,
      DrawCompletedEvent.OutputTuple,
      DrawCompletedEvent.OutputObject
    >;
    DrawCompleted: TypedContractEvent<
      DrawCompletedEvent.InputTuple,
      DrawCompletedEvent.OutputTuple,
      DrawCompletedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RaffleClosed(uint256)": TypedContractEvent<
      RaffleClosedEvent.InputTuple,
      RaffleClosedEvent.OutputTuple,
      RaffleClosedEvent.OutputObject
    >;
    RaffleClosed: TypedContractEvent<
      RaffleClosedEvent.InputTuple,
      RaffleClosedEvent.OutputTuple,
      RaffleClosedEvent.OutputObject
    >;

    "RaffleStarted(uint256)": TypedContractEvent<
      RaffleStartedEvent.InputTuple,
      RaffleStartedEvent.OutputTuple,
      RaffleStartedEvent.OutputObject
    >;
    RaffleStarted: TypedContractEvent<
      RaffleStartedEvent.InputTuple,
      RaffleStartedEvent.OutputTuple,
      RaffleStartedEvent.OutputObject
    >;

    "TicketPriceUpdated(uint256)": TypedContractEvent<
      TicketPriceUpdatedEvent.InputTuple,
      TicketPriceUpdatedEvent.OutputTuple,
      TicketPriceUpdatedEvent.OutputObject
    >;
    TicketPriceUpdated: TypedContractEvent<
      TicketPriceUpdatedEvent.InputTuple,
      TicketPriceUpdatedEvent.OutputTuple,
      TicketPriceUpdatedEvent.OutputObject
    >;

    "TicketPurchased(address,uint256,uint256)": TypedContractEvent<
      TicketPurchasedEvent.InputTuple,
      TicketPurchasedEvent.OutputTuple,
      TicketPurchasedEvent.OutputObject
    >;
    TicketPurchased: TypedContractEvent<
      TicketPurchasedEvent.InputTuple,
      TicketPurchasedEvent.OutputTuple,
      TicketPurchasedEvent.OutputObject
    >;

    "WinnerSelected(address,uint256,uint256)": TypedContractEvent<
      WinnerSelectedEvent.InputTuple,
      WinnerSelectedEvent.OutputTuple,
      WinnerSelectedEvent.OutputObject
    >;
    WinnerSelected: TypedContractEvent<
      WinnerSelectedEvent.InputTuple,
      WinnerSelectedEvent.OutputTuple,
      WinnerSelectedEvent.OutputObject
    >;
  };
}
